CREATE TABLE ORDERS (
    ID BIGINT AUTO_INCREMENT,
    CURRENCY_FROM VARCHAR(250) NOT NULL,
    CURRENCY_TO VARCHAR(250) NOT NULL,
    AMOUNT VARCHAR(150) NOT NULL,
    PENDING VARCHAR(150) NOT NULL,
    STATUS VARCHAR(150)  NOT NULL,
    TYPE VARCHAR(150)  NOT NULL,
    CREATED_AT DATE
);

ALTER TABLE ORDERS ADD ( CONSTRAINT ORDERS_PK PRIMARY KEY (ID) )
;