CREATE TABLE ORDERS_MAPPING (
    ID BIGINT AUTO_INCREMENT,
    ORDER_ID BIGINT NOT NULL,
    ORDER_ID_MATCH BIGINT NOT NULL,
    AMOUNT VARCHAR(150) NOT NULL,
    CREATED_AT DATE
);

ALTER TABLE ORDERS_MAPPING ADD ( CONSTRAINT ORDERS_MAPPING_PK PRIMARY KEY (ID) )
;